apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  template:
    spec:
      containers:
        - name: fastapi
          env:
            - name: APP_ENV
              value: prod
